volumes:
  mongodb_data:
    external: false
networks:
  cocoannotator:
    external: false

services:
  frontend:
    container_name: annotator_client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./client:/workspace/client"
    networks:
      - cocoannotator
    depends_on:
      - webserver
  ia:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    container_name: annotator_ia
    build:
      context: .
      dockerfile: ./backend/ia/Dockerfile
    ports:
      - 6000:6000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/ia:/workspace/ia"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=ia
      - FLASK_ENV=development
      - DEBUG=true
      - DEVICE=cuda
      # - SAM_MODEL_FILE=/models/sam_vit_b_01ec64.pth
      - SAM_MODEL_FILE=/models/sam_hq_vit_b.pth
      - SAM_MODEL_TYPE=vit_b
      # - DETECTRON2_FILE=/models/quick_schedules/mask_rcnn_R_50_FPN_inference_acc_test.yaml
      # - DETECTRON2_WEIGHTS=detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
      # - MASK_FORMER_FILE=/models/ade20k-150/maskformer_R50_bs16_160k.yaml
      # - MASK_FORMER_WEIGHTS=https://dl.fbaipublicfiles.com/maskformer/semantic-ade20k/maskformer_R50_bs16_160k/model_final_d8dbeb.pkl
      # - MASK_RCNN_FILE=/models/mask_rcnn_coco.h5
      # # Default coco classes (order matters)
      - |
        MASK_RCNN_CLASSES=
        BG,person,bicycle,car,motorcycle,airplane,
        bus,train,truck,boat,traffic light,
        fire hydrant,stop sign,parking meter,bench,bird,
        cat,dog,horse,sheep,cow,elephant,bear,
        zebra,giraffe,backpack,umbrella,handbag,tie,
        suitcase,frisbee,skis,snowboard,sports ball,
        kite,baseball bat,baseball glove,skateboard,
        surfboard,tennis racket,bottle,wine glass,cup,
        fork,knife,spoon,bowl,banana',apple,
        sandwich,orange,broccoli,carrot,hot dog,pizza,
        donut,cake,chair,couch,potted plant,bed,
        dining table,toilet,tv,laptop,mouse,remote,
        keyboard,cell phone,microwave,oven,toaster,
        sink,refrigerator,book,clock,vase,scissors,
        teddy bear,hair drier,toothbrush
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  webserver:
    container_name: annotator_webserver
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=development
      - DEBUG=true
      - DEVICE=cuda
      - |
        MASK_RCNN_CLASSES=
        BG,person,bicycle,car,motorcycle,airplane,
        bus,train,truck,boat,traffic light,
        fire hydrant,stop sign,parking meter,bench,bird,
        cat,dog,horse,sheep,cow,elephant,bear,
        zebra,giraffe,backpack,umbrella,handbag,tie,
        suitcase,frisbee,skis,snowboard,sports ball,
        kite,baseball bat,baseball glove,skateboard,
        surfboard,tennis racket,bottle,wine glass,cup,
        fork,knife,spoon,bowl,banana',apple,
        sandwich,orange,broccoli,carrot,hot dog,pizza,
        donut,cake,chair,couch,potted plant,bed,
        dining table,toilet,tv,laptop,mouse,remote,
        keyboard,cell phone,microwave,oven,toaster,
        sink,refrigerator,book,clock,vase,scissors,
        teddy bear,hair drier,toothbrush
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  workers:
    container_name: annotator_workers
    build:
      context: .
      dockerfile: ./backend/workers/Dockerfile
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
    depends_on:
      - messageq
      - database
    ports:
      - 5555:5555
    networks:
      - cocoannotator

  database:
    extends:
      file: ./mongo_and_rabbitmq-compose.yml
      service: database
  messageq:
    extends:
      file: ./mongo_and_rabbitmq-compose.yml
      service: messageq

