# To be used with docker-compose -f docker-compose.yml -f docker-compose.dev.yml [build|up|down|etc]

services:
  ia:
    environment:
      - FLASK_ENV=development
      - DEBUG=true
    # "" means run when no profile is specified
    profiles:
      - ""
  webserver:
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    image: "annotator_webclient:dev"
    environment:
      - FLASK_APP=webserver
      - FLASK_ENV=development
      - DEBUG=true