include:
  - ./docker-compose.yml

services:
  ia:
    environment:
      - FLASK_ENV=development
      - DEBUG=true
    # "" means run when no profile is specified
    profiles:
      - ""
  webserver:
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    environment:
      - FLASK_APP=webserver
      - FLASK_ENV=development
      - DEBUG=true